module.exports = [
  {
    id: 899,
    icon: 'home',
    name: '手动操控',
    router: '/',
  },
  {
    id: 900,
    icon: 'line-chart',
    name: '自动操控',
    router: '/main_2',
  },
  {
    id: 901,
    icon: 'clock-circle-o',
    name: '系统管理',
    router: '/manageStatus',
  },
  // {
  //   id: 902,
  //   icon: 'laptop',
  //   name: '数据库状态',
  //   router: '/databaseStatus',
  // }
  /*{
    id: 999,
    icon: 'home',
    name: '首页',
    router: '/',
  },
  {
    id: 1000,
    icon: 'trademark',
    name: '物联网2.0：数据自动化',
    router: '/iotTwo',
  },
  {
    id: 1001,
    icon: 'exclamation-circle-o',
    name: '物联网3.0：数据信息化处理',
    router: '/iotThree',
  },
  {
    id: 1002,
    icon: 'api',
    name: '物联网4.0：数据规律挖掘',
    router: '/iotFour',
  },*/
  /*{
    id: 1000,
    icon: 'home',
    name: '物联网2.0：数据自动化',
  },
  {
    id: 10003,
    bpid: 1000,
    mpid: 1000,
    name: '物联网商店',
    icon: 'switcher',
  },
  {
    id: 100031,
    bpid: 10003,
    mpid: 10003,
    name: '数据库状态',
    icon: 'paper-clip',
    router: '/warehouse/status',
  },
  {
    id: 1001,
    icon: 'api',
    name: '物联网3.0：数据信息化处理',
  },
  {
    id: 10011,
    bpid: 1001,
    mpid: 1001,
    name: '流式大数据处理',
    icon: 'laptop',
  },
  {
    id: 100111,
    bpid: 10011,
    mpid: 10011,
    name: '平台状态',
    icon: 'tags',
    router: '/stream/status',
  },
  {
    id: 100112,
    bpid: 10011,
    mpid: 10011,
    name: '全球洋流数据',
    icon: 'global',
    router: '/stream/nullschool',
  },
  {
    id: 1002,
    icon: 'database',
    name: '物联网4.0：数据规律挖掘',
  },
  {
    id: 10021,
    bpid: 1002,
    mpid: 1002,
    name: '雾计算',
    icon: 'cloud-o',
  },
  {
    id: 100211,
    bpid: 10021,
    mpid: 10021,
    name: '无线频谱监测',
    icon: 'wifi',
    router: '/fog/wireless',
  },
  /*
  {
    id: 1,
    icon: 'laptop',
    name: 'Dashboard',
    router: '/dashboard',
  },
  {
    id: 2,
    bpid: 1,
    name: 'Users',
    icon: 'user',
    router: '/user',
  },
  {
    id: 7,
    bpid: 1,
    name: 'Posts',
    icon: 'shopping-cart',
    router: '/post',
  },
  {
    id: 21,
    mpid: -1,
    bpid: 2,
    name: 'User Detail',
    router: '/user/:id',
  },
  {
    id: 3,
    bpid: 1,
    name: 'Request',
    icon: 'api',
    router: '/request',
  },
  {
    id: 4,
    bpid: 1,
    name: 'UI Element',
    icon: 'camera-o',
  },
  {
    id: 41,
    bpid: 4,
    mpid: 4,
    name: 'IconFont',
    icon: 'heart-o',
    router: '/UIElement/iconfont',
  },
  {
    id: 42,
    bpid: 4,
    mpid: 4,
    name: 'DataTable',
    icon: 'database',
    router: '/UIElement/dataTable',
  },
  {
    id: 43,
    bpid: 4,
    mpid: 4,
    name: 'DropOption',
    icon: 'bars',
    router: '/UIElement/dropOption',
  },
  {
    id: 44,
    bpid: 4,
    mpid: 4,
    name: 'Search',
    icon: 'search',
    router: '/UIElement/search',
  },
  {
    id: 45,
    bpid: 4,
    mpid: 4,
    name: 'Editor',
    icon: 'edit',
    router: '/UIElement/editor',
  },
  {
    id: 46,
    bpid: 4,
    mpid: 4,
    name: 'layer (Function)',
    icon: 'credit-card',
    router: '/UIElement/layer',
  },
  {
    id: 5,
    bpid: 1,
    name: 'Recharts',
    icon: 'code-o',
  },
  {
    id: 51,
    bpid: 5,
    mpid: 5,
    name: 'LineChart',
    icon: 'line-chart',
    router: '/chart/lineChart',
  },
  {
    id: 52,
    bpid: 5,
    mpid: 5,
    name: 'BarChart',
    icon: 'bar-chart',
    router: '/chart/barChart',
  },
  {
    id: 53,
    bpid: 5,
    mpid: 5,
    name: 'AreaChart',
    icon: 'area-chart',
    router: '/chart/areaChart',
  },
  {
    id: 6,
    bpid: 1,
    name: 'Test Navigation',
    icon: 'setting',
  },
  {
    id: 61,
    bpid: 6,
    mpid: 6,
    name: 'Test Navigation1',
    router: '/navigation/navigation1',
  },
  {
    id: 62,
    bpid: 6,
    mpid: 6,
    name: 'Test Navigation2',
    router: '/navigation/navigation2',
  },
  {
    id: 621,
    bpid: 62,
    mpid: 62,
    name: 'Test Navigation21',
    router: '/navigation/navigation2/navigation1',
  },
  {
    id: 622,
    bpid: 62,
    mpid: 62,
    name: 'Test Navigation22',
    router: '/navigation/navigation2/navigation2',
  },
  */
]
